### ISSUE TITLE
Can TSScall be used to call PolII reads clusters using proseq data?

### ISSUE THREAD

**Issue by cxue** [lavenderca/TSScall#7]
Hi, Lavenderca,
      Because TSScall provide the information of START-seq reads clusters, I am wondering whether it can be used to extend to call gro-/pro-seq reads clusters from gro-/proseq-data. If yes, it would be extend the usage of TSScall. Is it right?

    best
   Cheng Xue

**Comment by lavenderca** [comment]
Hi, Cheng,

We developed TSScall to work specifically with Start-seq data.  While the algorithm used by TSScall could likely be applied to other techniques, we haven't tested this.  If applied to other methods, like GRO-seq or PRO-seq, I would take care in evaluating the results.

Best,

Andy

**Comment by cxue** [comment]
Hi, Andy,
     Thank you for your response. In my understanding, TSScall calls the cluster of START-seq peak reads, and then get the uTSS and annotated TSS. In gro-seq/pro-seq, TSScall calls the cluster of PolII reads, which is similar to STAR-seq with the similar input. The difference is that START-seq reads focus on TSS while gro-seq/pro-seq reads show the location of PolII. I just hope that TSScall can provide some peak cluster of PolII.  Can I do it using TSScall? or could you recommend some revision processes or other software to do this. Thanks!!

    best
    Cheng

**Comment by lavenderca** [comment]
I would personally recommend Homer.  It uses a pretty straightforward method for calling TSSs from GRO-seq data that may work for PRO-seq.  You could also try groHMM, which is part of Bioconductor.

Andy

**Comment by cxue** [comment]
Thank you!!
